package com.breeze.metadata;

/**
 * @author IdeaBlade
 *
 */
public enum AutoGeneratedKeyType {
	/**
	 * Key is NOT autogenerated.
	 */
	None, 
	/**
	 * Key is automatically generated on the database server
	 */
	Identity, 
	/**
	 * Key is generated by an IKeyGenerator implementation on the server. 
	 */
	KeyGenerator
}
