package com.breeze.metadata;

import java.util.List;

import com.breeze.metadata.AutoGeneratedKeyType;

/**
 * Metadata description of an EntityType
 * @author IdeaBlade
 *
 */
public interface IEntityType {
	/**
	 * @return The name of the EntityType
	 */
	public String getName();
	/**
	 * @param propertyName The name of the property to be returned.
	 * @return
	 */
	public IProperty getProperty(String propertyName);
	public boolean isComplexType();
	public AutoGeneratedKeyType getAutoGeneratedKeyType();
	public List<IDataProperty> getKeyProperties();
}




