package com.breeze.metadata;

import java.util.List;

import com.breeze.metadata.AutoGeneratedKeyType;

public interface IEntityType {
	public String getName();
	public IProperty getProperty(String propertyName);
	public boolean isComplexType();
	public AutoGeneratedKeyType getAutoGeneratedKeyType();
	public List<IDataProperty> getKeyProperties();
}




