package com.breeze.metadata;

import com.breeze.metadata.AutoGeneratedKeyType;

public interface IEntityType {
	public String getName();
	public IProperty getProperty(String propertyName);
	public boolean isComplexType();
	public AutoGeneratedKeyType getAutoGeneratedKeyType();
}




